projects:
  default:
    schemaPath: "../backend/database/schema.graphql"
    includes: ["../backend/**/*.graphql"]
    extensions:
      endpoints:
        default:
          url: "http://localhost:4444/graphql"
          headers:
            APIAuthToken: 'eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhdXNlciJ9.RT46w06Uu_vLu7vD3DcLCVvEmbfeXcIbS-KR2u68_OGUrEIavQa6PUWfZOBBTMIE'
