projects:
  prisma:
    schemaPath: "../backend/src/generated/prisma.graphql"
    extensions:
      #prisma: "../backend/prisma.yml"
      endpoints:
        default:
          url: "http://localhost:4466/react-prisma-base/dev"
          headers:
            authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNlcnZpY2UiOiJyZWFjdC1wcmlzbWEtYmFzZUBkZXYiLCJyb2xlcyI6WyJhZG1pbiJdfSwiaWF0IjoxNTgyMTM4NzcwLCJleHAiOjE1ODI3NDM1NzB9.YFm7PdK7D4kHklexAARF0SpXuTSRwUCTcBkLTHYwhIg"

